name: Discord Push Notifications

on:
  push:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Discord Webhook
        uses: johnnyhuy/actions-discord-git-webhook@v1.0.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
